link to question https://www.hackerrank.com/challenges/weather-observation-station-5/problem
SELECT CITY, LENGTH(CITY) FROM STATION
WHERE CITY = 
(SELECT CITY FROM STATION ORDER BY LENGTH(CITY), CITY LIMIT 1);
SELECT CITY, LENGTH(CITY) FROM STATION
WHERE CITY = 
(SELECT CITY FROM STATION ORDER BY LENGTH(CITY) DESC, CITY LIMIT 1);